### ISSUE TITLE
Alpine uses a weak umask

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/image-terraform#37]
umask needs to be set to `027`

**Comment by timroster** [comment]
@triceam resolving this at the point of running the automation (vs. systemwide in the container which could have side-effects in alpine) could be done through a combination of dotfiles and ENV, BASH_ENV statements or script at ENTRYPOINT

It may be better to use one of ENV, BASH_ENV - but I see an inconsistency in the shells set in ENTRYPOINT - for `terraform` and `cli-tools-core` it is `/bin/bash` but for `cli-tools` it is `/bin/sh` . Is there a reason that `cli-tools` differs?

**Comment by timroster** [comment]
This also affects Fedora which also defaults to `022` . Investigating how the `cluster` modules are creating the config files. Rather than blast these changes across all of the container images, it may be better to properly set the permissions of sensitive files which are handled by the automation running process `uid` only.

**Comment by timroster** [comment]
Testing setting this through an additional `.bashrc` file along with others copied to `$HOME` in **cli-tools-core**. There will need to be an update to `Containerfile` in the **cli-tools** to make ENTRYPOINT consistent. So once testing is showing value I'll proceed with that first, followed by the **cli-tools-core** change.
